version: "3.9"
services:
  client:
    build: client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
  api-proxy:
    build: api-proxy
    ports:
      - "5000:5000" 
    volumes:
      - ./api-proxy/src:/app/src
  tile-server:
    image: klokantech/tileserver-gl
    ports:
      - "8080:80"
    volumes:
      - ./tile-server/:/data

