version: "3.9"

services:
  
  client:
    build: client
    container_name: client
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
  
  api-proxy:
    build: api-proxy
    container_name: api-proxy
    ports:
      - 5000:5000
    volumes:
      - ./api-proxy/src:/app/src
  
  # tile-server:
  #   image: maptiler/tileserver-gl
  #   container_name: tile-server
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ./tile-server/:/data

