version: "3.9"

services:

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    container_name: client
    restart: always
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.client.entrypoints=websecure"
      - "traefik.http.routers.client.rule=Host(`${DOMAIN}`)" 
      - "traefik.http.routers.client.tls.certresolver=myresolver"

  api-proxy:
    build:
      context: ./api-proxy
      dockerfile: Dockerfile.prod
    container_name: api-proxy
    restart: always
    expose: 
      - 5000
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.api-proxy.entrypoints=websecure"
      - "traefik.http.routers.api-proxy.rule=(Host(`${DOMAIN}`) && PathPrefix(`/api`))" 
      - "traefik.http.routers.api-proxy.tls.certresolver=myresolver"

  # tile-server:
  #   image: maptiler/tileserver-gl
  #   container_name: tile-server
  #   restart: always
  #   volumes:
  #     - ./tile-server/:/data
  #   command: --mbtiles slovenia.mbtiles --verbose --public_url=https://${DOMAIN}/tiles/
  #   expose: 
  #     - 8080
  #   labels: 
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.tile-server.entrypoints=websecure"
  #     - "traefik.http.routers.tile-server.rule=(Host(`${DOMAIN}`) && PathPrefix(`/tiles`))" 
  #     - "traefik.http.routers.tile-server.middlewares=tile-server-stripprefix"
  #     - "traefik.http.routers.tile-server.tls.certresolver=myresolver"
  #     - "traefik.http.middlewares.tile-server-stripprefix.stripprefix.prefixes=/tiles"
  #     - "traefik.http.middlewares.test-http-cache.plugin.httpCache.maxTtl=10000000"
  #     - "traefik.http.middlewares.test-http-cache.plugin.httpCache.memory.limit=2Gi"

  reverse-proxy:
    image: traefik:v2.9
    container_name: "traefik"
    restart: always
    ports: 
      - 443:443
      - 80:80
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./letsencrypt:/letsencrypt"
    command:
      # - "--log.level=DEBUG" 
      - "--providers.docker=true" 
      - "--providers.docker.exposedbydefault=false" 
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"